### ISSUE TITLE
error compilation with ARDUINO MEGA 2560

### ISSUE THREAD

**Issue by rems78** [flav1972/ArduinoINA219#10]
Hi,
With IDE arduino, select Mega 2560 as board  . Compilation error : 
Arduino : 1.8.9 (Windows 10), Carte : "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"
---
D:\ArduinoINA219-master\INA219.cpp:51:15: error: expected unqualified-id before numeric constant
 const uint8_t PG1 = 12;
               ^
D:\ArduinoINA219-master\INA219.cpp:52:15: error: expected unqualified-id before numeric constant
 const uint8_t PG0 = 11;
               ^
Utilisation de la bibliothèque Wire version 1.0 dans le dossier: D:\prog\arduino-1.8.9\hardware\arduino\avr\libraries\Wire 
exit status 1
Erreur de compilation pour la carte Arduino/Genuino Mega or Mega 2560
-----------------
error solved renaming PG1 and PG2.
Effetc?
Regards

**Comment by flav1972** [comment]
Hello,

I do not have a Mega to try it.

Regards,
Flav

**Comment by flav1972** [comment]
Merged the pull request in master.

**Comment by flav1972** [comment]
Merged the pull request in master. v1.0.4
